dist: xenial
language: go
go: "1.13.x"
env:
  - GO111MODULE=on
cache:
  directories:
    - $GOPATH/pkg/mod
    - $HOME/.cache/go-build
install: true
before_script:
- GO111MODULE=off go get -u github.com/golangci/golangci-lint/cmd/golangci-lint
script:
- golangci-lint run
- go test -race ./...
deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux
