language: go
go: 1.11.5
before_install:
- go get github.com/golang/dep/cmd/dep
install:
- dep ensure
before_script:
- GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -gcflags=-e -o /dev/null
- curl -L https://git.io/vp6lP | sh
- PATH=~/bin:$PATH gometalinter --config=gometalinter.json
script: go test -v -race ./...
deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux
