language: go
go: 1.11.1
before_install:
- go get github.com/golang/dep/cmd/dep
install:
- dep ensure
before_script:
- GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -gcflags=-e -o /dev/null
- go get github.com/alecthomas/gometalinter
- gometalinter --install
- gometalinter --config=gometalinter.json
- go get golang.org/x/tools/cmd/cover
- go get github.com/mattn/goveralls
script: goveralls -v -race -package ./...
deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux
