[[constraint]]
  branch = "master"
  name = "github.com/cenkalti/backoff"

[[constraint]]
  branch = "master"
  name = "github.com/cenkalti/log"

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/go-homedir"

[[constraint]]
  branch = "master"
  name = "github.com/zeebo/bencode"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.2.1"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  branch = "master"
  name = "github.com/hashicorp/go-multierror"

[[constraint]]
  name = "go.etcd.io/bbolt"
  version = "1.3.0"

[[constraint]]
  name = "github.com/urfave/cli"
  version = "1.20.0"

[[constraint]]
  name = "github.com/chihaya/chihaya"
  version = "1.0.2"
