[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  branch = "master"
  name = "github.com/cenkalti/backoff"

[[constraint]]
  branch = "master"
  name = "github.com/cenkalti/log"

[[constraint]]
  branch = "master"
  name = "github.com/zeebo/bencode"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.2.1"

[[constraint]]
  name = "github.com/boltdb/bolt"
  version = "1.3.1"

[[constraint]]
  name = "github.com/urfave/cli"
  version = "1.20.0"

[[constraint]]
  name = "github.com/chihaya/chihaya"
  branch = "master"

[[constraint]]
  branch = "master"
  name = "github.com/hokaccha/go-prettyjson"

[[constraint]]
  name = "github.com/jroimartin/gocui"
  version = "0.4.0"

[[constraint]]
  name = "github.com/fatih/structs"
  version = "1.1.0"

[[constraint]]
  name = "github.com/mitchellh/go-homedir"
  version = "1.0.0"

[[constraint]]
  branch = "package"
  name = "github.com/cenkalti/boltbrowser"

[[constraint]]
  branch = "master"
  name = "github.com/nictuku/dht"

[[constraint]]
  name = "github.com/powerman/rpc-codec"
  version = "1.0.0"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "1.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/google/btree"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"
